"""schema inicial

Revision ID: 08ef2221d8ba
Revises:
Create Date: 2026-03-02 22:54:45.312045

"""
from collections.abc import Sequence

import geoalchemy2
import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08ef2221d8ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensões exigidas pelo schema (VECTOR, Geography/PostGIS, gin_trgm_ops).
    # IF NOT EXISTS: no-op quando já criadas pelo bootstrap (init_extensions.sql
    # via docker-entrypoint-initdb.d). Torna `alembic upgrade head` self-contained
    # em ambiente novo onde o papel de migration tem privilégio de superusuário.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guarnicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_guarnicoes_desativado_por_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_guarnicoes_ativo'), 'guarnicoes', ['ativo'], unique=False)
    op.create_table('legislacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lei', sa.String(length=100), nullable=False),
    sa.Column('artigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislacoes_lei'), 'legislacoes', ['lei'], unique=False)
    op.create_index('uq_legislacao_lei_artigo', 'legislacoes', ['lei', 'artigo'], unique=True)
    op.create_table('passagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lei', sa.String(length=100), nullable=False),
    sa.Column('artigo', sa.String(length=50), nullable=False),
    sa.Column('nome_crime', sa.String(length=300), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passagens_lei'), 'passagens', ['lei'], unique=False)
    op.create_index('uq_passagem_lei_artigo', 'passagens', ['lei', 'artigo'], unique=True)
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('cpf_encrypted', sa.Text(), nullable=True),
    sa.Column('cpf_hash', sa.String(length=64), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('apelido', sa.String(length=100), nullable=True),
    sa.Column('foto_principal_url', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.Column('guarnicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_pessoas_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_hash')
    )
    op.create_index('idx_pessoa_guarnicao', 'pessoas', ['guarnicao_id'], unique=False)
    op.create_index('idx_pessoa_nome_trgm', 'pessoas', ['nome'], unique=False, postgresql_using='gin', postgresql_ops={'nome': 'gin_trgm_ops'})
    op.create_index(op.f('ix_pessoas_ativo'), 'pessoas', ['ativo'], unique=False)
    op.create_index(op.f('ix_pessoas_guarnicao_id'), 'pessoas', ['guarnicao_id'], unique=False)
    op.create_index(op.f('ix_pessoas_nome'), 'pessoas', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('guarnicao_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_usuarios_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    op.create_index(op.f('ix_usuarios_matricula'), 'usuarios', ['matricula'], unique=True)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.Column('guarnicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_veiculos_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_veiculo_guarnicao', 'veiculos', ['guarnicao_id'], unique=False)
    op.create_index(op.f('ix_veiculos_ativo'), 'veiculos', ['ativo'], unique=False)
    op.create_index(op.f('ix_veiculos_guarnicao_id'), 'veiculos', ['guarnicao_id'], unique=False)
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)
    op.create_table('abordagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('localizacao', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('endereco_texto', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.Column('guarnicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_abordagens_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abordagem_client_id', 'abordagens', ['client_id'], unique=True, postgresql_where='client_id IS NOT NULL')
    op.create_index('idx_abordagem_guarnicao_data', 'abordagens', ['guarnicao_id', 'data_hora'], unique=False)
    op.create_index('idx_abordagem_localizacao', 'abordagens', ['localizacao'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_abordagens_ativo'), 'abordagens', ['ativo'], unique=False)
    op.create_index(op.f('ix_abordagens_data_hora'), 'abordagens', ['data_hora'], unique=False)
    op.create_index(op.f('ix_abordagens_guarnicao_id'), 'abordagens', ['guarnicao_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('recurso', sa.String(length=100), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_acao'), 'audit_logs', ['acao'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.create_table('enderecos_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('localizacao', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_enderecos_pessoa_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_pessoa_ativo'), 'enderecos_pessoa', ['ativo'], unique=False)
    op.create_table('abordagem_passagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abordagem_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('passagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passagem_id'], ['passagens.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_abordagem_passagem', 'abordagem_passagens', ['abordagem_id', 'passagem_id', 'pessoa_id'], unique=True)
    op.create_table('abordagem_pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abordagem_id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_abordagem_pessoa', 'abordagem_pessoas', ['abordagem_id', 'pessoa_id'], unique=True)
    op.create_table('abordagem_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abordagem_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_abordagem_veiculo', 'abordagem_veiculos', ['abordagem_id', 'veiculo_id'], unique=True)
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo_url', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('abordagem_id', sa.Integer(), nullable=True),
    sa.Column('embedding_face', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('face_processada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagens.id'], ),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_fotos_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_ativo'), 'fotos', ['ativo'], unique=False)
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ocorrencia', sa.String(length=50), nullable=False),
    sa.Column('abordagem_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_pdf_url', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('processada', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.Column('guarnicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abordagem_id'], ['abordagens.id'], ),
    sa.ForeignKeyConstraint(['desativado_por_id'], ['usuarios.id'], name='fk_ocorrencias_desativado_por_id', use_alter=True),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocorrencias_ativo'), 'ocorrencias', ['ativo'], unique=False)
    op.create_index(op.f('ix_ocorrencias_guarnicao_id'), 'ocorrencias', ['guarnicao_id'], unique=False)
    op.create_index(op.f('ix_ocorrencias_numero_ocorrencia'), 'ocorrencias', ['numero_ocorrencia'], unique=True)
    op.create_table('relacionamento_pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id_a', sa.Integer(), nullable=False),
    sa.Column('pessoa_id_b', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.Integer(), nullable=False),
    sa.Column('primeira_abordagem_id', sa.Integer(), nullable=False),
    sa.Column('ultima_abordagem_id', sa.Integer(), nullable=False),
    sa.Column('primeira_vez', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_vez', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pessoa_id_a < pessoa_id_b', name='ck_relacionamento_order'),
    sa.ForeignKeyConstraint(['pessoa_id_a'], ['pessoas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pessoa_id_b'], ['pessoas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primeira_abordagem_id'], ['abordagens.id'], ),
    sa.ForeignKeyConstraint(['ultima_abordagem_id'], ['abordagens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id_a', 'pessoa_id_b', name='uq_relacionamento')
    )
    op.create_index('idx_relacionamento_freq', 'relacionamento_pessoas', ['frequencia'], unique=False)
    op.create_index(op.f('ix_relacionamento_pessoas_pessoa_id_a'), 'relacionamento_pessoas', ['pessoa_id_a'], unique=False)
    op.create_index(op.f('ix_relacionamento_pessoas_pessoa_id_b'), 'relacionamento_pessoas', ['pessoa_id_b'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Neutralizado (achado #27/2026-07-13): esta é a migration inicial —
    # down_revision=None, ou seja, "downgrade" daqui significa apagar TODAS
    # as tabelas da aplicação (abordagens, pessoas, usuarios, veiculos, etc.)
    # E remover as extensões vector/postgis/pg_trgm. O corpo autogerado
    # original ainda piorava isso: tentava recriar manualmente tabelas
    # internas do Tiger Geocoder do PostGIS (place_lookup, zip_state_loc,
    # pagc_lex, countysub_lookup, ...) via op.create_table — essas tabelas só
    # devem ser criadas pela própria extensão postgis_tiger_geocoder; recriá-las
    # à mão deixa o catálogo da extensão inconsistente com o schema real,
    # potencialmente quebrando qualquer uso futuro de PostGIS mesmo após
    # reinstalar a extensão.
    #
    # `alembic downgrade` desta revisão nunca é a operação certa em produção.
    # Se o objetivo é reverter uma migration recente, faça downgrade só até
    # a revisão anterior a ela (nunca até base). Se o objetivo é
    # genuinamente descartar o banco inteiro, use o runbook de restore
    # (scripts/restore_from_backup.sh / docs/disaster-recovery.md) ou
    # `DROP DATABASE` explícito — nunca um downgrade Alembic silencioso.
    raise NotImplementedError(
        "Downgrade da migration inicial (08ef2221d8ba) foi desativado de propósito: "
        "apagaria TODAS as tabelas da aplicação e deixaria o catálogo do PostGIS "
        "inconsistente (recriação manual de tabelas do Tiger Geocoder). Para "
        "descartar o banco de verdade, use scripts/restore_from_backup.sh ou "
        "DROP DATABASE explícito — não um downgrade Alembic. Ver comentário "
        "acima (achado #27, code review de segurança 2026-07-13)."
    )
