"""Adiciona coluna nomes_envolvidos à tabela ocorrencias.

Coluna TEXT nullable para armazenar nomes dos envolvidos na ocorrência
separados por pipe (ex: "João Silva|Maria Souza"). Parsing para list[str]
é feito pelo schema OcorrenciaRead.

Revision ID: 32f74a0867c0
Revises: b7162740aeeb
Create Date: 2026-03-09 13:20:49.562833

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32f74a0867c0"
down_revision: str | None = "b7162740aeeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ocorrencias", sa.Column("nomes_envolvidos", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ocorrencias", "nomes_envolvidos")
    # ### end Alembic commands ###
