"""adicionar vinculos manuais

Revision ID: 48e9ff4bf4be
Revises: 4d259d0fa8ae
Create Date: 2026-03-14 16:21:39.167501

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48e9ff4bf4be"
down_revision: str | None = "4d259d0fa8ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vinculos_manuais",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pessoa_id", sa.Integer(), nullable=False),
        sa.Column("pessoa_vinculada_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("desativado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desativado_por_id", sa.Integer(), nullable=True),
        sa.Column("guarnicao_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("pessoa_id != pessoa_vinculada_id", name="ck_vinculo_manual_diferente"),
        sa.ForeignKeyConstraint(
            ["desativado_por_id"],
            ["usuarios.id"],
            name="fk_vinculos_manuais_desativado_por_id",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["guarnicao_id"],
            ["guarnicoes.id"],
        ),
        sa.ForeignKeyConstraint(["pessoa_id"], ["pessoas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pessoa_vinculada_id"], ["pessoas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pessoa_id", "pessoa_vinculada_id", name="uq_vinculo_manual"),
    )
    op.create_index("idx_vinculo_manual_pessoa", "vinculos_manuais", ["pessoa_id"], unique=False)
    op.create_index(
        "idx_vinculo_manual_vinculada", "vinculos_manuais", ["pessoa_vinculada_id"], unique=False
    )
    op.create_index(op.f("ix_vinculos_manuais_ativo"), "vinculos_manuais", ["ativo"], unique=False)
    op.create_index(
        op.f("ix_vinculos_manuais_guarnicao_id"), "vinculos_manuais", ["guarnicao_id"], unique=False
    )
    op.create_index(
        op.f("ix_vinculos_manuais_pessoa_id"), "vinculos_manuais", ["pessoa_id"], unique=False
    )
    op.create_index(
        op.f("ix_vinculos_manuais_pessoa_vinculada_id"),
        "vinculos_manuais",
        ["pessoa_vinculada_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vinculos_manuais_pessoa_vinculada_id"), table_name="vinculos_manuais")
    op.drop_index(op.f("ix_vinculos_manuais_pessoa_id"), table_name="vinculos_manuais")
    op.drop_index(op.f("ix_vinculos_manuais_guarnicao_id"), table_name="vinculos_manuais")
    op.drop_index(op.f("ix_vinculos_manuais_ativo"), table_name="vinculos_manuais")
    op.drop_index("idx_vinculo_manual_vinculada", table_name="vinculos_manuais")
    op.drop_index("idx_vinculo_manual_pessoa", table_name="vinculos_manuais")
    op.drop_table("vinculos_manuais")
    # ### end Alembic commands ###
