"""adicionar_veiculo_id_em_fotos

Revision ID: 4d259d0fa8ae
Revises: d5730d65225c
Create Date: 2026-03-14 12:35:49.294335

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d259d0fa8ae"
down_revision: str | None = "d5730d65225c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_abordagem_veiculo_pessoa"), table_name="abordagem_veiculos")
    op.create_index(
        op.f("ix_abordagem_veiculos_pessoa_id"), "abordagem_veiculos", ["pessoa_id"], unique=False
    )
    op.add_column("fotos", sa.Column("veiculo_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_fotos_veiculo_id"), "fotos", ["veiculo_id"], unique=False)
    op.create_foreign_key(
        "fk_fotos_veiculo_id_veiculos",
        "fotos",
        "veiculos",
        ["veiculo_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_fotos_veiculo_id_veiculos", "fotos", type_="foreignkey")
    op.drop_index(op.f("ix_fotos_veiculo_id"), table_name="fotos")
    op.drop_column("fotos", "veiculo_id")
    op.drop_index(op.f("ix_abordagem_veiculos_pessoa_id"), table_name="abordagem_veiculos")
    op.create_index(
        op.f("idx_abordagem_veiculo_pessoa"), "abordagem_veiculos", ["pessoa_id"], unique=False
    )
    # ### end Alembic commands ###
