"""adicionar estado em enderecos_pessoa

Revision ID: 4f6309edf92f
Revises: 1862e349651c
Create Date: 2026-03-03 11:12:17.262968

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f6309edf92f"
down_revision: str | None = "1862e349651c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("enderecos_pessoa", sa.Column("estado", sa.String(length=2), nullable=True))
    op.alter_column("usuarios", "guarnicao_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usuarios", "guarnicao_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("enderecos_pessoa", "estado")
    # ### end Alembic commands ###
