"""Adiciona coluna data_ocorrencia à tabela ocorrencias.

Coluna DATE não-nula para registrar a data real do fato policial,
que pode diferir de criado_em (data de cadastro no sistema). Utiliza
server_default=CURRENT_DATE para compatibilidade com linhas existentes.

Revision ID: 7e93f610776f
Revises: 32f74a0867c0
Create Date: 2026-03-09 20:31:33.088802

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e93f610776f"
down_revision: str | None = "32f74a0867c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adiciona coluna data_ocorrencia à tabela ocorrencias."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ocorrencias",
        sa.Column(
            "data_ocorrencia",
            sa.Date(),
            nullable=False,
            server_default=sa.text("CURRENT_DATE"),
        ),
    )
    # Remove server_default após backfill para evitar silenciar erros de INSERT
    op.alter_column("ocorrencias", "data_ocorrencia", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove coluna data_ocorrencia da tabela ocorrencias."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ocorrencias", "data_ocorrencia")
    # ### end Alembic commands ###
