"""adicionar pessoa_veiculos

Revision ID: 9a9e5535d7b3
Revises: d10f90d496ce
Create Date: 2026-07-04 13:11:56.989221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9e5535d7b3'
down_revision: Union[str, None] = 'd10f90d496ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('desativado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desativado_por_id', sa.Integer(), nullable=True),
    sa.Column('guarnicao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['guarnicao_id'], ['guarnicoes.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id', 'veiculo_id', name='uq_pessoa_veiculo')
    )
    # FK desativado_por_id -> usuarios.id criada separadamente: um
    # ForeignKeyConstraint com use_alter=True inline em op.create_table()
    # é descartado silenciosamente pelo compilador de DDL do SQLAlchemy
    # (use_alter só é honrado no caminho de MetaData.create_all(), não em
    # Table.create() isolado, que é o que op.create_table() usa por baixo
    # dos panos). Mesmo padrão adotado em
    # 0193ae0cadf6_add_bpm_table_and_bpm_id_to_guarnicoes.py.
    op.create_foreign_key(
        'fk_pessoa_veiculos_desativado_por_id',
        'pessoa_veiculos', 'usuarios',
        ['desativado_por_id'], ['id'],
    )
    op.create_index(op.f('ix_pessoa_veiculos_ativo'), 'pessoa_veiculos', ['ativo'], unique=False)
    op.create_index(op.f('ix_pessoa_veiculos_guarnicao_id'), 'pessoa_veiculos', ['guarnicao_id'], unique=False)
    op.create_index(op.f('ix_pessoa_veiculos_pessoa_id'), 'pessoa_veiculos', ['pessoa_id'], unique=False)
    op.create_index(op.f('ix_pessoa_veiculos_veiculo_id'), 'pessoa_veiculos', ['veiculo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pessoa_veiculos_veiculo_id'), table_name='pessoa_veiculos')
    op.drop_index(op.f('ix_pessoa_veiculos_pessoa_id'), table_name='pessoa_veiculos')
    op.drop_index(op.f('ix_pessoa_veiculos_guarnicao_id'), table_name='pessoa_veiculos')
    op.drop_index(op.f('ix_pessoa_veiculos_ativo'), table_name='pessoa_veiculos')
    op.drop_constraint('fk_pessoa_veiculos_desativado_por_id', 'pessoa_veiculos', type_='foreignkey')
    op.drop_table('pessoa_veiculos')
    # ### end Alembic commands ###
