"""add totp_secret usuario

Revision ID: a9f77a36acfb
Revises: f78ad28021fe
Create Date: 2026-06-03 13:20:31.579323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f77a36acfb'
down_revision: Union[str, None] = 'f78ad28021fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('totp_secret', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'totp_secret')
    # ### end Alembic commands ###
