"""ocorrencia_abordagem_id_nullable

Revision ID: b7162740aeeb
Revises: d594993f0855
Create Date: 2026-03-09 12:51:43.265547

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7162740aeeb"
down_revision: str | None = "d594993f0855"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ocorrencias", "abordagem_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ocorrencias", "abordagem_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
