"""add senha_expira_em usuario

Revision ID: f78ad28021fe
Revises: 6531e2eeac14
Create Date: 2026-06-03 13:06:32.895277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78ad28021fe'
down_revision: Union[str, None] = '6531e2eeac14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha_expira_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'senha_expira_em')
    # ### end Alembic commands ###
