apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-argus         # UID fixo — referenciado nos alertas e dashboard
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
